Alembic inntal setup
zimba-real-estate-investment-engine/zimba-rei-common-components pull request #6
Opened 2024-10-26 07:21 UTC by Claire56

Created 

- model file
- database file
- alembic.ini
- elembic/env.py
- Generated an empty migration list and populated i with information 
- unable to run alembic migrate head 
```bash
sqlalchemy.exc.OperationalError: (pymysql.err.OperationalError) (1045, "Access denied for user 'rei_app_rds_user'@'c-98-45-159-92.hsd1.ca.comcast.net' (using password: YES)")
```

2024-10-30 14:36 UTC, joshkafeero requested changes
@Claire56 , I think you said this was a WIP, just a comment, where are the tests. 

- They'll help others know how to use these tools. We should have tests/database folder with the tests for the various components.
-  Not good to run the app to find out if the app is running. Just pytest on the test folder will give us the assurance we need that things are OK.

2024-11-01 02:04 UTC, Claire56 commented
> @Claire56 , I think you said this was a WIP, just a comment, where are the tests.
> 
> * They'll help others know how to use these tools. We should have tests/database folder with the tests for the various components.
> * Not good to run the app to find out if the app is running. Just pytest on the test folder will give us the assurance we need that things are OK.

Sure, added a connection test file, will create a testDB for detailed alembic tests , I accidentally run pytest on the actual database and it deleted the subscrition table, so expect two alembic revisions , one is to create table and the other is to recreate the table

2024-11-06 18:26 UTC, zimba-github approved these changes
We want out tests in a dedicated folder. We don't want test code in the code distribution. We'll leak stuff like auth details and other related issues. Also tests being able to resolve references dependencies will mean everything works well for other client components such as dagster and others. I will create a ticket for this purpose.

2024-11-06 18:26 UTC, zimba-github commented on database/testdb.py
We want out tests in a dedicated folder. We don't want test code in the code distribution. We'll leak stuff like auth details and other related issues. Also tests being able to resolve references dependencies will mean everything works well for other client components such as dagster and others.

2024-11-06 18:27 UTC, merged